// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAJQji0VTxL-Ahsj5miLgf-r8CUBbqVd44',
    appId: '1:1050007373901:web:dcae20b59b76abe6457404',
    messagingSenderId: '1050007373901',
    projectId: 'info-uang',
    authDomain: 'info-uang.firebaseapp.com',
    storageBucket: 'info-uang.firebasestorage.app',
    measurementId: 'G-F8JHVFGW94',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCKQoN7HpsF6_sKp2TtSpv5xEjuEacltpg',
    appId: '1:1050007373901:android:e88c26f54bf34c21457404',
    messagingSenderId: '1050007373901',
    projectId: 'info-uang',
    storageBucket: 'info-uang.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBOxZEadNJWidFYAGFs7S9VmPkByjMux4U',
    appId: '1:1050007373901:ios:da9c7a9d59e7bb07457404',
    messagingSenderId: '1050007373901',
    projectId: 'info-uang',
    storageBucket: 'info-uang.firebasestorage.app',
    iosBundleId: 'com.example.fisrtProject',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBOxZEadNJWidFYAGFs7S9VmPkByjMux4U',
    appId: '1:1050007373901:ios:da9c7a9d59e7bb07457404',
    messagingSenderId: '1050007373901',
    projectId: 'info-uang',
    storageBucket: 'info-uang.firebasestorage.app',
    iosBundleId: 'com.example.fisrtProject',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAJQji0VTxL-Ahsj5miLgf-r8CUBbqVd44',
    appId: '1:1050007373901:web:2b25ab761dbb7504457404',
    messagingSenderId: '1050007373901',
    projectId: 'info-uang',
    authDomain: 'info-uang.firebaseapp.com',
    storageBucket: 'info-uang.firebasestorage.app',
    measurementId: 'G-RZF7ZNL613',
  );
}
